---
- name: Patch Ubuntu system
  hosts: ubuntu
  become: true
  gather_facts: yes
  tasks:
    - name: "Patching Time"
      debug:
        msg:
          - timestamp: "{{ ansible_date_time.iso8601_micro }}"
      run_once: true

    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes
